config/routes.rb
Rails.application.routes.draw do
  resources :employees, except: :show do
    Deductions::TYPES.each do |advance|
      resources advance, except: :show
    end

    Payslips::TYPES.each do |payslip|
      resources payslip, except: %i(edit update)
    end

    get :attendances, to: 'attendances#index'
  end

  Deductions::TYPES.each do |advance|
    resources advance, only: %i(index show edit update destroy)
  end

  Payslips::TYPES.each do |payslip|
    resources payslip, only: %i(index show destroy)
  end

  post :attendances, to: 'attendances#create'

  root to: 'employees#index'
end

app/models/employee.rb
class Employee < ApplicationRecord
  enum rate_type: SalaryTypes.keys
  enum status: %i(active inactive)

  validates :name, presence: true
  validates :rate, numericality: { greater_than: 0 }
  validates :overtime_rate, numericality: { greater_than: 0 }
  validates :rice_allowance_rate, numericality: { greater_than: 0 }
  validates :month_end_rate, numericality: { allow_nil: true }
  validates :year_end_rate, numericality: { allow_nil: true }
  validates :rate_type, inclusion: { in: rate_types.keys, message: :invalid }

  after_validation :set_cash_bond

  has_many :salary_advances, dependent: :nullify do
    def applies_for(type, period)
      where(salary_advances: { salary_type: type, applies_on: period })
    end
  end
  has_many :salary_payslips, dependent: :nullify

  has_many :rice_allowance_advances, dependent: :nullify do
    def applies_for(period)
      where(rice_allowance_advances: { applies_on: period })
    end
  end
  has_many :rice_allowance_payslips, dependent: :nullify

  has_many :overtime_payslips, dependent: :nullify

  has_many :month_end_advances, dependent: :nullify do
    def applies_for(period)
      where(month_end_advances: { applies_on: period })
    end
  end
  has_many :month_end_payslips, dependent: :nullify

  has_many :year_end_advances, dependent: :nullify do
    def applies_for(period)
      where(year_end_advances: { applies_on: period })
    end
  end
  has_many :year_end_payslips, dependent: :nullify
  has_many :attendances, dependent: :destroy do
    def for(type, start_date, end_date)
      clause = where(attendance_type: type)
      clause = clause.where('applies_on >= ?', start_date) if start_date.present?
      clause = clause.where('applies_on <= ?', end_date) if end_date.present?
      clause = clause.order(applies_on: :desc)
      clause
    end
  end

  scope :name_like, ->(name) { where('name ILIKE ?', "%#{name}%") }

  def self.search(name: nil, rate_type: nil)
    scope = where(nil)
    scope = scope.merge(Employee.name_like(name)) if name.present?
    scope = scope.where(rate_type: rate_type) if rate_type.present?
    scope
  end

  def has_month_end?
    month_end_rate.present? && !month_end_rate.zero?
  end

  def has_year_end?
    year_end_rate.present? && !year_end_rate.zero?
  end

  def disallowed?(type)
    type = type.to_s.gsub(/_(payslips|advances)$/, '')
    !public_send("has_#{type}?") if respond_to?("has_#{type}?")
  end

  private

  def set_cash_bond
    self.cash_bond = false if !half_monthly?
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    scope = params[:name].present? || params[:rate_type].present? ?
      Employee.search(name: params[:name], rate_type: params[:rate_type]) :
      Employee.all
    scope = scope.order(created_at: :desc)
    @pagy, @employees = pagy(scope, page: params[:page], items: 25)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: 'Record saved successfully!'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])

    if @employee.update_attributes(employee_params)
      redirect_to employees_path, notice: 'Record saved successfully!'
    end
  end

  def destroy
    employee = Employee.find(params[:id])
    employee.destroy if employee
    redirect_to employees_path, notice: 'Record deleted successfully!'
  end

  private

  def employee_params
    params.require(:employee).permit(
      :name,
      :rate_type,
      :rate,
      :overtime_rate,
      :rice_allowance_rate,
      :month_end_rate,
      :year_end_rate,
      :status,
      :cash_bond
    )
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def info_pill?
    controller_name == 'employees'
  end

  def deductions_pill?
    employee_tab? && Deductions.include?(controller_name)
  end

  def payslips_pill?
    employee_tab? && Payslips.include?(controller_name)
  end

  def attendances_pill?
    employee_tab? && controller_name === 'attendances'
  end
end

app/views/employees/_create_advance_dropdown.html.erb
<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= label %></button>
<div class="dropdown-menu">
  <%- Deductions::TYPES.each do |advance| -%>
    <%- next if employee.disallowed? advance -%>
    <%= link_to advance.to_s.titleize,
      public_send("new_employee_#{advance.to_s.singularize}_path", employee),
      class: 'dropdown-item'
    %>
  <%- end -%>
</div>

app/views/employees/_create_payslip_dropdown.html.erb
<button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= label %></button>
<div class="dropdown-menu">
  <%- Payslips::TYPES.each do |payslip| -%>
    <%- next if employee.disallowed? payslip -%>
    <%= link_to payslip.to_s.titleize,
      public_send("new_employee_#{payslip.to_s.singularize}_path", employee),
      class: 'dropdown-item'
    %>
  <%- end -%>
</div>

app/views/employees/_form_buttons.html.erb
<div class="d-flex">
  <div class="p-2">
    <%= f.primary 'Save', data: { 'disable-with': 'Saving...' } %>
  </div>
  <%- unless @employee.new_record? -%>
    <div class="p-2">
      <%= render 'create_advance_dropdown',
        label: '&plus; Advance'.html_safe, employee: @employee %>
    </div>
    <div class="p-2">
      <%= render 'create_payslip_dropdown',
        label: '&plus; Payslip'.html_safe, employee: @employee %>
    </div>
    <div class="ml-auto p-2">
      <%= link_to 'Delete', employee_path(@employee),
        remote: true,
        method: :delete,
        data: {
          confirm: 'Are you sure you want to delete this record?'
        },
        class: 'btn btn-danger' %>
    </div>
  <%- end -%>
</div>

app/views/employees/attendances.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'employees/nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <h4 class="mb-3">
          Attendance for <%= @employee.name %>
        </h4>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Date</th>
                <th scope="col">Attendance</th>
              </tr>
            </thead>
            <tbody>
              <% @attendances.each do |attendance| %>
                <tr>
                  <td><%= l attendance.applies_on, format: :short %></td>
                  <td><%= number_with_precision attendance.amount, precision: 2 %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="row">
          <div class="col-auto mr-auto">
            <nav aria-label="Attendance list navigation">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/attendances.js.erb
$('[data-attendance-sum]').val("<%= @attendances.sum(:amount) %>")

app/views/employees/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="row">
  <div class="col-lg-12">
  <div class="mb-2">
    <%= bootstrap_form_with(
      data: { turbolinks: true },
      url: employees_path,
      method: :get,
      local: true,
      layout: :inline
    ) do |f| %>
      <div class="input-group mr-2">
        <%= f.select :rate_type,
          rate_types_for_select,
          { selected: params[:rate_type], include_blank: true },
          data: { toggler: true }
        %>
      </div>
      <div>
        <%= f.submit 'Search', class: 'btn btn-info' %>
      </div>
    <% end %>
  </div>
    <div>
      <table class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Rate</th>
            <th scope="col">Rate Type</th>
            <th scope="col">Rice Allowance</th>
            <th scope="col">Overtime</th>
            <th scope="col">Month End</th>
            <th scope="col">Year End</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <tr class="<%= 'table-warning' if employee.inactive? %>">
              <th scope="row"><%= employee.name %></th>
              <td><%= number_to_currency employee.rate %></td>
              <td><%= employee.rate_type.humanize %></td>
              <td><%= number_to_currency employee.rice_allowance_rate %></td>
              <td><%= number_to_currency employee.overtime_rate %></td>
              <td>
                <%= employee.has_month_end? ?
                  number_to_currency(employee.month_end_rate) :
                  'N/A'
                %>
              </td>
              <td>
                <%= employee.has_year_end? ?
                  number_to_currency(employee.year_end_rate) :
                  'N/A'
                %>
              </td>
              <td>
                <div class="btn-group btn-group-sm" role="group">
                  <%= link_to 'Edit', edit_employee_path(employee),
                    class: 'btn btn-secondary p-2' %>
                  <%= link_to 'Delete', employee_path(employee),
                    remote: true,
                    method: :delete,
                    data: {
                      confirm: 'Are you sure you want to delete this record?'
                    },
                    class: 'btn btn-danger p-2' %>
                  <div class="btn-group">
                    <%= render 'create_advance_dropdown',
                      label: '&plus; Advance'.html_safe, employee: employee %>
                  </div>
                  <div class="btn-group" role="group">
                    <%= render 'create_payslip_dropdown',
                      label: '&plus; Payslip'.html_safe, employee: employee %>
                  </div>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-auto mr-auto">
        <nav aria-label="Employee list navigation">
          <%= pagy_bootstrap_nav(@pagy).html_safe %>
        </nav>
      </div>
      <div class="col-auto">
        <%= link_to 'Add new employee',
          new_employee_path(@employee), class: 'btn btn-secondary' %>
      </div>
    </div>
  </div>
</div>

app/views/employees/overtime_payslips.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'employees/nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <h4 class="mb-3">
          Overtime payslips for <%= @employee.name %>
        </h4>
        <%= render 'shared/payslips/search_form',
          url: nesting_aware_overtime_payslips_path,
          type: :weekly %>
        <%= render 'shared/payslips/table' %>
        <div class="row">
          <div class="col-auto mr-auto">
            <nav aria-label="Payslips list navigation">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </nav>
          </div>
          <div class="col-auto">
            <%= link_to 'Create new overtime payslip',
              new_employee_overtime_payslip_path(@employee),
              class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/rice_allowance_advances.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'employees/nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <h4 class="mb-3">
          Rice allowance advances for <%= @employee.name %>
        </h4>
        <%= render 'shared/advances/search_form',
          url: nesting_aware_rice_allowance_advances_path,
          type: :weekly %>
        <%= render 'shared/advances/table' %>
        <div class="row">
          <div class="col-auto mr-auto">
            <nav aria-label="Advances list navigation">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </nav>
          </div>
          <div class="col-auto">
            <%= link_to 'Create new rice allowance advance',
              new_employee_rice_allowance_advance_path(@employee), class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/rice_allowance_payslips.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'employees/nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <h4 class="mb-3">
          Rice allowance payslips for <%= @employee.name %>
        </h4>
        <%= render 'shared/payslips/search_form',
          url: nesting_aware_rice_allowance_payslips_path,
          type: :weekly %>
        <%= render 'shared/payslips/table' %>
        <div class="row">
          <div class="col-auto mr-auto">
            <nav aria-label="Payslips list navigation">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </nav>
          </div>
          <div class="col-auto">
            <%= link_to 'Create new rice allowance payslip',
              new_employee_rice_allowance_payslip_path(@employee),
              class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/salary_payslips.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'employees/nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <h4 class="mb-3">
          Salary payslips for <%= @employee.name %>
        </h4>
        <%= render 'shared/payslips/search_form',
          url: nesting_aware_salary_payslips_path,
          selected: params[:range] || @employee.rate_type,
          type: %i(weekly half_monthly) %>
        <%= render 'salary_payslips/table' %>
        <div class="row">
          <div class="col-auto mr-auto">
            <nav aria-label="Payslips list navigation">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </nav>
          </div>
          <div class="col-auto">
            <%= link_to 'Create new salary payslip',
              new_employee_salary_payslip_path(@employee),
              class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/update.js.erb
$("#employee-form").replaceWith("<%= j render 'form' %>");

app/views/employees/year_end_advances.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'employees/nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <h4 class="mb-3">
          Year end advances for <%= @employee.name %>
        </h4>
        <%= render 'shared/advances/search_form',
          url: nesting_aware_year_end_advances_path,
          type: :yearly %>
        <%= render 'shared/advances/table' %>
        <div class="row">
          <div class="col-auto mr-auto">
            <nav aria-label="Advances list navigation">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </nav>
          </div>
          <div class="col-auto">
            <%= link_to 'Create new year end advance',
              new_employee_year_end_advance_path(@employee), class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/year_end_payslips.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= render 'employees/nav_pills' %>
    <div class="tab-content">
      <div class="tab-pane active">
        <h4 class="mb-3">
          Year end payslips for <%= @employee.name %>
        </h4>
        <%= render 'shared/payslips/search_form',
          url: nesting_aware_year_end_payslips_path,
          type: :yearly %>
        <%= render 'shared/payslips/table' %>
        <div class="row">
          <div class="col-auto mr-auto">
            <nav aria-label="Payslips list navigation">
              <%= pagy_bootstrap_nav(@pagy).html_safe %>
            </nav>
          </div>
          <div class="col-auto">
            <%= link_to 'Create new year end payslip',
              new_employee_year_end_payslip_path(@employee),
              class: 'btn btn-secondary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>